export const ABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "balances",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "contribute",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "contributions",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "_round", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "_contributions",
        type: "tuple[]",
        internalType: "struct IChama.Contribution[]",
        components: [
          {
            name: "memberId",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "member", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "round", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createGroup",
    inputs: [
      {
        name: "_group",
        type: "tuple",
        internalType: "struct IChama.CreateGroupParams",
        components: [
          { name: "name", type: "string", internalType: "string" },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
          { name: "vault", type: "address", internalType: "address" },
          {
            name: "maxMembers",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cycleDays",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "contributionAmount",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "joinFee", type: "uint256", internalType: "uint256" },
          { name: "lateFee", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "distribute",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getGroup",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IChama.GroupParams",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "name", type: "string", internalType: "string" },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "vault", type: "address", internalType: "address" },
          {
            name: "memberId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cycleDays",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxMembers",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "contributionAmount",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "joinFee", type: "uint256", internalType: "uint256" },
          { name: "lateFee", type: "uint256", internalType: "uint256" },
          {
            name: "currentRound",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "groupId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "groups",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "name", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "creator", type: "address", internalType: "address" },
      { name: "vault", type: "address", internalType: "address" },
      { name: "memberId", type: "uint256", internalType: "uint256" },
      { name: "cycleDays", type: "uint256", internalType: "uint256" },
      { name: "maxMembers", type: "uint256", internalType: "uint256" },
      {
        name: "contributionAmount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "joinFee", type: "uint256", internalType: "uint256" },
      { name: "lateFee", type: "uint256", internalType: "uint256" },
      { name: "currentRound", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "joinGroup",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "members",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "_members",
        type: "tuple[]",
        internalType: "struct IChama.Member[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "member", type: "address", internalType: "address" },
          { name: "groupId", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "payouts",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "_payouts",
        type: "tuple[]",
        internalType: "struct IChama.MemberPayout[]",
        components: [
          {
            name: "memberId",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "member", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "round", type: "uint256", internalType: "uint256" },
          { name: "paid", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundBalance",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "_round", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setGroupActive",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGroupInactive",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPayoutOrder",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "_rounds", type: "uint256[]", internalType: "uint256[]" },
      { name: "_members", type: "address[]", internalType: "address[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Contributed",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GroupCreated",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "name",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "creator",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GroupJoined",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "JoinFeePaid",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Payout",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AllRoundsPaid", inputs: [] },
  { type: "error", name: "AlreadyContributed", inputs: [] },
  { type: "error", name: "AlreadyMember", inputs: [] },
  { type: "error", name: "AlreadyPaid", inputs: [] },
  { type: "error", name: "ContributionAmountZero", inputs: [] },
  { type: "error", name: "CycleDaysZero", inputs: [] },
  {
    type: "error",
    name: "DuplicatePayoutMember",
    inputs: [{ name: "member", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ExcessContribution",
    inputs: [
      { name: "required", type: "uint256", internalType: "uint256" },
      { name: "excess", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "GroupFull", inputs: [] },
  { type: "error", name: "GroupInactive", inputs: [] },
  { type: "error", name: "GroupNotFound", inputs: [] },
  { type: "error", name: "GroupStarted", inputs: [] },
  { type: "error", name: "InsufficientContribution", inputs: [] },
  { type: "error", name: "InsufficientJoinFee", inputs: [] },
  {
    type: "error",
    name: "InsuffientPayoutAmount",
    inputs: [
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "payout", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "InvalidMembers", inputs: [] },
  { type: "error", name: "InvalidPayoutMember", inputs: [] },
  { type: "error", name: "MaxMembersZero", inputs: [] },
  { type: "error", name: "NotCreator", inputs: [] },
  { type: "error", name: "NotMember", inputs: [] },
  { type: "error", name: "RoundsMembersMismatch", inputs: [] },
  {
    type: "error",
    name: "UknownMember",
    inputs: [{ name: "member", type: "address", internalType: "address" }],
  },
];
